#![allow(clippy::exhaustive_enums, reason = "Generated by sol! macro")]
#![allow(clippy::exhaustive_structs, reason = "Generated by sol! macro")]

//! Wallet setup script for automated Polymarket trading.
//!
//! This script performs ALL one-time setup needed for an EOA wallet:
//!   1. Checks USDC and pUSD balances
//!   2. Wraps USDC → pUSD via CollateralOnramp (Polymarket's V2 collateral)
//!   3. Approves pUSD for CTF Exchange, Neg Risk Exchange, and Neg Risk Adapter
//!   4. Approves Conditional Tokens (ERC-1155) for all three contracts
//!   5. Derives API credentials for CLOB authentication
//!
//! Usage:
//!   POLYMARKET_PRIVATE_KEY=0x... cargo run --example setup_wallet --all-features
//!
//! Dry run (shows what would happen without executing):
//!   POLYMARKET_PRIVATE_KEY=0x... cargo run --example setup_wallet --all-features -- --dry-run

use std::env;
use std::str::FromStr as _;

use alloy::primitives::{U160, U256};
use alloy::providers::ProviderBuilder;
use alloy::signers::Signer as _;
use alloy::signers::local::LocalSigner;
use alloy::sol;
use polymarket_client_sdk_v2::clob::{Client as ClobClient, Config as ClobConfig};
use polymarket_client_sdk_v2::types::{Address, address};
use polymarket_client_sdk_v2::{POLYGON, PRIVATE_KEY_VAR, contract_config};

// ─── Contract Addresses (Polygon Mainnet) ───────────────────────────────────

/// Native USDC on Polygon
const USDC: Address = address!("0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359");

/// USDC.e (bridged) on Polygon — also accepted by CollateralOnramp
const USDC_E: Address = address!("0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174");

/// pUSD — Polymarket's V2 collateral token
const PUSD: Address = address!("0xC011a7E12a19f7B1f670d46F03B03f3342E82DFB");

/// CollateralOnramp — wraps USDC.e → pUSD
const COLLATERAL_ONRAMP: Address = address!("0x93070a847efEf7F70739046A929D47a521F5B8ee");

/// Uniswap V3 SwapRouter on Polygon (for USDC → USDC.e swap)
const UNISWAP_V3_ROUTER: Address = address!("0xE592427A0AEce92De3Edee1F18E0157C05861564");

const DEFAULT_RPC_URL: &str = "https://polygon.llamarpc.com"; // override via POLYGON_RPC_URL env var
const CLOB_URL: &str = "https://clob.polymarket.com";

// ─── ABI Interfaces ─────────────────────────────────────────────────────────

sol! {
    #[sol(rpc)]
    interface IERC20 {
        function approve(address spender, uint256 value) external returns (bool);
        function allowance(address owner, address spender) external view returns (uint256);
        function balanceOf(address account) external view returns (uint256);
        function decimals() external view returns (uint8);
        function transfer(address to, uint256 value) external returns (bool);
    }

    #[sol(rpc)]
    interface IERC1155 {
        function setApprovalForAll(address operator, bool approved) external;
        function isApprovedForAll(address account, address operator) external view returns (bool);
    }

    #[sol(rpc)]
    interface ICollateralOnramp {
        function wrap(address asset, address to, uint256 amount) external;
    }

    #[sol(rpc)]
    interface ISwapRouter {
        struct ExactInputSingleParams {
            address tokenIn;
            address tokenOut;
            uint24 fee;
            address recipient;
            uint256 deadline;
            uint256 amountIn;
            uint256 amountOutMinimum;
            uint160 sqrtPriceLimitX96;
        }
        function exactInputSingle(ExactInputSingleParams calldata params) external payable returns (uint256 amountOut);
    }
}


#[tokio::main]
async fn main() -> anyhow::Result<()> {
    dotenvy::dotenv().ok();
    tracing_subscriber::fmt::init();

    let args: Vec<String> = env::args().collect();
    let dry_run = args.iter().any(|arg| arg == "--dry-run");

    let private_key = env::var(PRIVATE_KEY_VAR)
        .or_else(|_| env::var("POLYMARKET_PRIVATE_KEY"))
        .expect("Need POLYMARKET_PRIVATE_KEY environment variable");

    let signer = LocalSigner::from_str(&private_key)?.with_chain_id(Some(POLYGON));
    let owner = signer.address();

    let rpc_url = env::var("POLYGON_RPC_URL").unwrap_or_else(|_| DEFAULT_RPC_URL.to_string());

    println!("\n======= Polymarket Wallet Setup =======\n");
    println!("  Wallet:  {owner}");
    println!("  Chain:   Polygon (137)");
    println!("  RPC:     {rpc_url}");
    println!("  Mode:    {}\n", if dry_run { "DRY RUN" } else { "LIVE" });

    // ─── Step 1: Check Balances ─────────────────────────────────────────────

    println!("━━━ Step 1: Checking Balances ━━━\n");

    let provider = ProviderBuilder::new()
        .wallet(signer.clone())
        .connect(&rpc_url)
        .await?;

    let usdc_token = IERC20::new(USDC, provider.clone());
    let usdc_e_token = IERC20::new(USDC_E, provider.clone());
    let pusd_token = IERC20::new(PUSD, provider.clone());

    let usdc_bal = usdc_token.balanceOf(owner).call().await.unwrap_or_default();
    let usdc_e_bal = usdc_e_token.balanceOf(owner).call().await.unwrap_or_default();
    let pusd_bal = pusd_token.balanceOf(owner).call().await.unwrap_or_default();

    let usdc_human = format_usdc(usdc_bal);
    let usdc_e_human = format_usdc(usdc_e_bal);
    let pusd_human = format_usdc(pusd_bal);

    println!("  USDC (native):  ${usdc_human}");
    println!("  USDC.e:         ${usdc_e_human}");
    println!("  pUSD:           ${pusd_human}");
    println!();

    // ─── Step 2: Convert USDC → pUSD ──────────────────────────────────────────

    println!("━━━ Step 2: Converting USDC → pUSD ━━━\n");

    if usdc_e_bal > U256::ZERO {
        // USDC.e → pUSD via CollateralOnramp (direct wrap)
        println!("  Wrapping USDC.e ${} → pUSD (via CollateralOnramp)", format_usdc(usdc_e_bal));

        if !dry_run {
            let approve_token = IERC20::new(USDC_E, provider.clone());
            println!("  → Approving CollateralOnramp to spend USDC.e...");
            let tx = approve_token
                .approve(COLLATERAL_ONRAMP, usdc_e_bal)
                .send()
                .await?
                .watch()
                .await?;
            println!("    ✓ Approved (tx: {tx})");

            let onramp = ICollateralOnramp::new(COLLATERAL_ONRAMP, provider.clone());
            println!("  → Wrapping USDC.e → pUSD...");
            let tx = onramp
                .wrap(USDC_E, owner, usdc_e_bal)
                .send()
                .await?
                .watch()
                .await?;
            println!("    ✓ Wrapped (tx: {tx})");

            let new_pusd = pusd_token.balanceOf(owner).call().await.unwrap_or_default();
            println!("    New pUSD balance: ${}", format_usdc(new_pusd));
        } else {
            println!("    [DRY RUN] Would approve + wrap ${}", format_usdc(usdc_e_bal));
        }
        println!();
    } else if usdc_bal > U256::ZERO {
        // Native USDC → USDC.e (swap) → pUSD (wrap)
        // CollateralOnramp only accepts USDC.e, so we swap native USDC first
        println!("  Converting native USDC ${} → USDC.e → pUSD", format_usdc(usdc_bal));
        println!("  Step A: Swap USDC → USDC.e via Uniswap V3");
        println!("  Step B: Wrap USDC.e → pUSD via CollateralOnramp\n");

        if !dry_run {
            // Step A: Approve Uniswap V3 Router to spend native USDC
            let usdc_contract = IERC20::new(USDC, provider.clone());
            println!("  → Approving Uniswap V3 Router...");
            let tx = usdc_contract
                .approve(UNISWAP_V3_ROUTER, usdc_bal)
                .send()
                .await?
                .watch()
                .await?;
            println!("    ✓ Approved (tx: {tx})");

            // Swap native USDC → USDC.e via exactInputSingle
            let router = ISwapRouter::new(UNISWAP_V3_ROUTER, provider.clone());
            let deadline = U256::from(chrono::Utc::now().timestamp() as u64 + 300);
            // 0.01% fee tier pool (stablecoin pair)
            let fee: u32 = 100;
            // Accept up to 0.5% slippage on a stablecoin swap
            let min_out = usdc_bal * U256::from(995) / U256::from(1000);

            println!("  → Swapping USDC → USDC.e (fee tier: {}bps, min out: ${})...",
                fee / 100, format_usdc(min_out));

            let params = ISwapRouter::ExactInputSingleParams {
                tokenIn: USDC,
                tokenOut: USDC_E,
                fee: fee.try_into().unwrap(),
                recipient: owner,
                deadline,
                amountIn: usdc_bal,
                amountOutMinimum: min_out,
                sqrtPriceLimitX96: U160::ZERO,
            };

            let tx = router
                .exactInputSingle(params)
                .send()
                .await?
                .watch()
                .await?;
            println!("    ✓ Swapped (tx: {tx})");

            // Check USDC.e balance after swap
            let usdc_e_after = usdc_e_token.balanceOf(owner).call().await.unwrap_or_default();
            println!("    USDC.e balance: ${}", format_usdc(usdc_e_after));

            // Step B: Wrap USDC.e → pUSD
            if usdc_e_after > U256::ZERO {
                let approve_token = IERC20::new(USDC_E, provider.clone());
                println!("  → Approving CollateralOnramp for USDC.e...");
                let tx = approve_token
                    .approve(COLLATERAL_ONRAMP, usdc_e_after)
                    .send()
                    .await?
                    .watch()
                    .await?;
                println!("    ✓ Approved (tx: {tx})");

                let onramp = ICollateralOnramp::new(COLLATERAL_ONRAMP, provider.clone());
                println!("  → Wrapping USDC.e → pUSD...");
                let tx = onramp
                    .wrap(USDC_E, owner, usdc_e_after)
                    .send()
                    .await?
                    .watch()
                    .await?;
                println!("    ✓ Wrapped (tx: {tx})");

                let new_pusd = pusd_token.balanceOf(owner).call().await.unwrap_or_default();
                println!("    New pUSD balance: ${}", format_usdc(new_pusd));
            }
        } else {
            println!("    [DRY RUN] Would swap ${} USDC → USDC.e → pUSD", format_usdc(usdc_bal));
        }
        println!();
    } else if pusd_bal > U256::ZERO {
        println!("  ✓ Already have ${pusd_human} pUSD. No conversion needed.\n");
    } else {
        println!("  ⚠ No USDC or pUSD found. Deposit USDC to this wallet first.\n");
    }

    // ─── Step 3: Set Token Approvals ────────────────────────────────────────

    println!("━━━ Step 3: Setting Token Approvals ━━━\n");

    let config = contract_config(POLYGON, false).unwrap();
    let neg_risk_config = contract_config(POLYGON, true).unwrap();

    let targets: Vec<(&str, Address)> = {
        let mut v = vec![
            ("CTF Exchange V2", config.exchange),
            
        ];
        if let Some(adapter) = neg_risk_config.neg_risk_adapter {
            v.push(("Neg Risk Adapter", adapter));
        }
        v
    };

    let pusd_contract = IERC20::new(PUSD, provider.clone());
    let ctf = IERC1155::new(config.conditional_tokens, provider.clone());

    for (name, target) in &targets {
        println!("  [{name}] → {target}");

        // Check current pUSD allowance
        let allowance = pusd_contract
            .allowance(owner, *target)
            .call()
            .await
            .unwrap_or_default();

        if allowance >= U256::from(u128::MAX) {
            println!("    pUSD: already approved (max)");
        } else {
            if !dry_run {
                let tx = pusd_contract
                    .approve(*target, U256::MAX)
                    .send()
                    .await?
                    .watch()
                    .await?;
                println!("    pUSD: ✓ approved (tx: {tx})");
            } else {
                println!("    pUSD: [DRY RUN] would approve unlimited");
            }
        }

        // Check CTF (ERC-1155) approval
        let ctf_approved = ctf
            .isApprovedForAll(owner, *target)
            .call()
            .await
            .unwrap_or_default();

        if ctf_approved {
            println!("    CTF:  already approved");
        } else {
            if !dry_run {
                let tx = ctf
                    .setApprovalForAll(*target, true)
                    .send()
                    .await?
                    .watch()
                    .await?;
                println!("    CTF:  ✓ approved (tx: {tx})");
            } else {
                println!("    CTF:  [DRY RUN] would setApprovalForAll");
            }
        }
        println!();
    }

    // ─── Step 4: Derive API Credentials ─────────────────────────────────────

    println!("━━━ Step 4: Deriving API Credentials ━━━\n");

    if !dry_run {
        let config = ClobConfig::builder().use_server_time(true).build();
        match ClobClient::new(CLOB_URL, config)?
            .authentication_builder(&signer)
            .authenticate()
            .await
        {
            Ok(client) => {
                println!("  ✓ CLOB authentication successful!");
                match client.api_keys().await {
                    Ok(keys) => println!("  ✓ API keys active: {keys:?}"),
                    Err(e) => println!("  ⚠ Could not list API keys: {e}"),
                }
            }
            Err(e) => {
                println!("  ✗ Authentication failed: {e}");
                println!("    This may mean your wallet needs to interact with Polymarket first.");
                println!("    Try depositing via polymarket.com or the Bridge API.");
            }
        }
    } else {
        println!("  [DRY RUN] Would authenticate with CLOB and derive API keys");
    }

    // ─── Summary ────────────────────────────────────────────────────────────

    println!("\n━━━ Setup Complete ━━━\n");
    if dry_run {
        println!("  This was a DRY RUN. Re-run without --dry-run to execute.");
    } else {
        println!("  Your wallet is ready for automated trading!");
        println!("  Start the bot with: cargo run --release");
    }
    println!();

    Ok(())
}

fn format_usdc(raw: U256) -> String {
    let divisor = U256::from(1_000_000u64); // 6 decimals
    let whole = raw / divisor;
    let frac = (raw % divisor).to::<u64>();
    format!("{}.{:02}", whole, frac / 10_000)
}

